### ISSUE TITLE
Update VCEP gene list used for VCEP ClinVar reports

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-ep-reports#1]
Updated gene list can be found in [this](https://drive.google.com/drive/folders/1lBwtsjYPUTioUQssI_5DU7kmL2_ciZJV?usp=sharing) folder .

**Comment by larrybabb** [comment]
@toneillbroad can you give me a sense of how difficult this task is? If it is minor can you squeeze it in and let me know. If it is not a super simple thing, just let me know and I'll prioritize it properly.

**Comment by toneillbroad** [comment]
Updating the gene list in the report is a simple task. Building the clinvar-reports container that runs the reports sometimes requires some effort as often packages that have been included in the container have changed or become outdate while building. TL;DR should only take an hour or so, but sometimes it takes 4 or more hours to sort through packages and container building issues. I'll get on it.
