### ISSUE TITLE
Add a list of all genes in scope for the VCEP Variant Tracker

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ep-reports#14]
All genes used to populate the report will be listed on the home tab - that way VCEPs will have a reference for what genes the report is focusing on, even if there aren't any alerts or priorities for one of the genes.

**Comment by larrybabb** [comment]
@dazzariti I added a gene list that incorporates and replaces the alert counts table on the home page. It should show all genes associated with the report along with the breakdown of alerts for the currently loaded release. Please verify and let me know if it suffices.

**Comment by dazzariti** [comment]
Perfect!
