### ISSUE TITLE
Permissions Warning when Refreshing Release Data on VCEP Variation Report

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ep-reports#16]
When a new user tries to refresh data they receive an error "Google hasn't verified this app. The app is requesting access to sensitive info in your Google account. Until the developer (lbabb@broadinstitute.org) verifies the app with Google, you shouldn't use it. 

![image](https://user-images.githubusercontent.com/10732982/206035129-cd9ab5c6-f4d1-49fb-a743-933b602752b5.png)

If we want people to accept this, we'll need to tell them explicitly what data we're capturing from their account. Would verifying the app with Google solve this?

Screen shot from Erin Riggs trying to refresh data in the Rett-Angelman report https://docs.google.com/spreadsheets/d/1pd7Yct3jqSLi0ks_Y4Ml87E8hI2CqfDNgkGAXEF0-Bk/edit?usp=sharing

**Comment by larrybabb** [comment]
@dazzariti I think I've got the Rett Angelman, Rasopathy and HL sheets setup to use the OAuth user permission list that is also used by the ClinVar Curator Chrome extension. I'd like to know if folks still get this screen. Can you ask Erin or someone else that is getting this screen to try again and let me know how it goes?

Here's the link to the GCP page that let's you manage the user list. https://console.cloud.google.com/apis/credentials/consent?project=clingen-dx

**Comment by dazzariti** [comment]
They are getting a different warning now:

If that's to be expected I think I should just add a note to the home tab and let anyone know if they aren't comfortable giving permission to the app, to contact me and I can refresh for them.

![image002](https://user-images.githubusercontent.com/10732982/210648449-34920c93-657b-4b3f-ad4a-eafb4ffeef29.png)
![image001](https://user-images.githubusercontent.com/10732982/210648452-b9b6974b-5bcd-4784-9f07-8cbb45359012.png)

**Comment by larrybabb** [comment]
I think I'll need to work with Steve Jahl next week to see if we can get this to work like the authorization for the ClinVar chrome extension. I think we should be able to get there. If you can keep the pilot users engaged until we have a chance to investigate further that would be ideal. Your proposal is a fine temporary plan but I would prefer to make this less ominous for new users.

**Comment by dazzariti** [comment]
I think this was solved by adding users to https://console.cloud.google.com/apis/credentials/consent?project=clingen-dx
