### ISSUE TITLE
EP Reports Error

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ep-reports#2]
EP Reports error has been occurring in production for two weeks since the last issue was completed.

Maybe a file format issue, since the last ticket was an update to the xlsx file, no code changes at all.

python3 EPReports.py
Traceback (most recent call last):
  File "EPReports.py", line 862, in <module>
    main()
  File "EPReports.py", line 858, in main
    create_geneList2(geneFile)
  File "EPReports.py", line 223, in create_geneList2
    wb = xlrd.open_workbook(vcep_org_file_xlsx)
  File "/Library/Python/3.8/site-packages/xlrd/__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported

**Comment by larrybabb** [comment]
@toneillbroad are you waiting on me to review something for this? or are you waiting for feedback from one of the users? In either case, let me know what is needed to progress this to "Closed".

**Comment by toneillbroad** [comment]
Wanted to see this run successfully through the automated report process. As of 5/7/2021 it has, so I will close.
