### ISSUE TITLE
Data "refresh" is broken on all VCEP reports

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-ep-reports#21]
I updated the procedure name that is used by all the sheets. And as such it broke everything. I am working on setting up a a temporary tool to update all the sheets with new queries for the datasource sheets connect to bigquery.

**Comment by larrybabb** [comment]
All VCEP reports have been updated. There is a new app script on the [ClinVar Report BQ Support Tables](https://docs.google.com/spreadsheets/d/1bADskBcobHTmmXungY09beWPDEa1nqM-PP__86yGVj0/edit#gid=2067576827) google sheet that will fix the sql statements on all VCEP reports based on hardcoded lists and configs in the app script.

Ideally we will continue moving this logic to be more dynamic (based on the data in the config sheet). Ryan and I are working to enhance the scripts and provide a menu so that non-tech folks can use this to generate and maintain reports.

**Comment by larrybabb** [comment]
@dazzariti would you please try to run the "Refresh" on several of the VCEP sheets to verify that this is fixed.

**Comment by dazzariti** [comment]
Tested it on three reports, seems to be working!
