### ISSUE TITLE
ClinVar Discrepancy Report Pilot - VCEPs

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/clinvar-ep-reports#5]
SP Ticket Link: https://broadinstitute.atlassian.net/jira/software/projects/CGSP/boards/872?issueParent=468029&selectedIssue=CGSP-422

**PRIORITY LEVEL:** Currently slated as first pilot report for development. Should be produced as a deliverable to Steven H. for review. 

**INFORMATION TO BE INCLUDED ON REPORT:**
**1. Classification outlier percentage** (as it's own field to make filterable)
**2. Variants which would be high priority for the VCEP to work on.** These variants have been defined previously as:
- ClinVar variants WITHOUT an Expert Panel submission, but in a gene in scope for the Expert Panel, with at least one P/LP submission and at least one VUS/LB/B submission (medically-significant conflict)
- ClinVar variants WITHOUT an Expert Panel submission, but in a gene in scope for the Expert Panel, with at least one VUS submission and at least one LB/B submission
- ClinVar variants WITHOUT an Expert Panel submission, but in a gene in scope for the Expert Panel, with ≥3 concordant VUS submissions from different submitters
- ClinVar variants WITHOUT an Expert Panel SCV, but in a gene in scope for the EP, with at least one P/LP submission from a no assertion criteria provided submitter (such as OMIM or GeneReviews).

Previous reports also included the following information:
- ClinVar variants classified by the Expert Panel with a DateLastEvaluated greater than 2 years from the date of the generated report
- ClinVar variants classified by the Expert Panel as P/LP AND a recent VUS/LB/B classification submitted from a non-Expert Panel submitter (with a DateLastEvaluated up to 1 year prior to the Expert Panel DateLastEvaluated)
- ClinVar variants classified by the Expert Panel as VUS AND a recent P/LP classification submitted from a non-Expert Panel submitter (with a DateLastEvaluated up to 1 year prior to the Expert Panel DateLastEvaluated)
- ClinVar variants classified by the Expert Panel as VUS AND a newer LB/B classification submitted from a non-Expert Panel submitter (with a DateLastEvaluated up to 1 year prior of Expert Panel DateLastEvaluated)

Baseline for [VCEP report](https://docs.google.com/spreadsheets/d/1QfAONTRt7vRftSt1x8CYqBq86eXLy_gdlXkJz584_2c/edit#gid=1486116726). 

**ADDITIONAL WISHLIST ITEMS/FUTURE CONSIDERATIONS:** 
1. Identify method in which to retain notes while also being able to add new entries to the report

**Comment by KelseaChang5** [comment]
Per Marina, the thing she would really like to see from these reports is a note on which entries are new. She would prioritize this over the function of note retention. 

We could also potentially present this pilot at the ClinGen Curation Tools Feedback on Thursdays once it's ready - would be a good way to get stakeholder feedback.

**Comment by dazzariti** [comment]
I think this ticket is redundant with more recent tickets and can be closed.
