### ISSUE TITLE
Update VCEP Gene List to inform VCEP reports

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ep-reports#6]
Here is the latest VCEP gene list, includes two new genes for the Hearing Loss VCEP https://docs.google.com/spreadsheets/d/1M98y9H5CfD2Mmlc3O0Hvwa-buUBcHyz3Nr8UUt5-LPI/edit?usp=sharing

**Per Marina no rush on this request, so can be completed after Discrepancy reports are in production and serve as the first piloted report**

**Comment by dazzariti** [comment]
@KelseaChang5 Not sure if this is the right place to add this request so tagging you to confirm.

This is based on the email from Marina:

I'm emailing because now that our expanded scope specs are approved for the HL VCEP, we would like to get back to curating discrepancies. Would you be able to send along the most recent discrepancy report that you have for HL? The most recent one I have was for August. If I could request that our two new approved genes (OTOF and MYO15A) could be included, that would be great.

**Comment by KelseaChang5** [comment]
@larrybabb you are able to run these reports manually correct? Would you be able to generate the report Marina is requesting above?

**Comment by larrybabb** [comment]
yes. i can. the process is to make sure the gene list in danielle's post above is accurate and then I can run the report. I'll sort it out.

**Comment by dazzariti** [comment]
Yes, that list is accurate (updated today)

**Comment by KelseaChang5** [comment]
@larrybabb Per Marina no rush on this request, so can be completed after Discrepancy reports are in production and serve as the first piloted report

**Comment by dazzariti** [comment]
Reviewed and this is completed - I will pass on updated report to Hearing Loss VCEP.
