### ISSUE TITLE
VCEP Variant Historical Report

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ep-reports#7]
Placeholder for the VCEP variant query discussed with Heidi at April 11th ClinGen Broad Weekly Meeting, priority is after first round of new discrepancy reports

Request: A list of VCEP approved variants and the the overall clinical significance in ClinVar for each variant PRIOR to a VCEP classification.

Here is the list of VCEP approved variants from ERepo, sorted by date last approved, column P (https://docs.google.com/spreadsheets/d/1B-oRM39FLNeSCiN9nPItxe70RmzyY9_hOpQVe3m5cBE/edit?usp=sharing). 

I believe the VCV xml data our ClinVar ingest is based on starts July 2019 - so if we assume for this analysis we’d want to look at the classification a month prior to each date last evaluated, there are more than 820 variants that wouldn’t be captured by the ClinVar ingest.

Another thing that I’m not sure how to get at is which of these variants have been recurated by the VCEP, in those cases I think we only have the most recent date last evaluated - so we’d need to discuss if there’s a way to identify which variants have been recurated and if we can pull the earliest date last evaluated for each variant.

**Comment by KelseaChang5** [comment]
Per Heidi this is a priority but can wait until after the discrepancy reports are released/in-production
